name: Setup Python

description: 'Setup environment'
runs:
  using: 'composite'
  steps:
    # https://python-poetry.org/docs/#ci-recommendations
    - name: Install poetry
      run: pipx install poetry==1.8.3
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install
      shell: bash
