[tool.poetry]
authors = []
description = ""
name = "wizishop"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.8.2"
httpx = "^0.25.2"

[tool.poetry.group.dev.dependencies]
ruff = "0.5.7"
mypy = "1.11.1"
pytest = "8.3.2"
python-dotenv = "1.0.1"

[tool.ruff]
output-format = "concise"

[tool.ruff.lint]
select = [
    "E", "W",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
    "PL",  # Pylint
]
ignore = [
    "PLR0913",  # Too many arguments in function definition
]
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["PLR2004"]  # Magic value used in comparison

[tool.mypy]
strict = true
