[tool.poetry]
name = "wizishop"
version = "0.1.1"
description = ""
authors = ["Julien Pillaud <julien.pillaud@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.7.4"
httpx = "^0.25.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.0"
mypy = "^1.10.1"
pytest = "^8.2.2"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = [
    "E", "W",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
    "PL",  # Pylint
]
ignore = [
    "PLR0913",  # Too many arguments in function definition
    "PLC0414"  # Import alias does not rename original package
]
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["PLR2004"]  # Magic value used in comparison

[tool.mypy]
strict = true
