name: CI

on: [push, pull_request]

jobs:
  lint:
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run linter and type checker
        run: |
          uv run ruff format .
          uv run ruff check .
          uv run mypy .

      - name: Minimize uv cache
        run: uv cache prune --ci

  tests:
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        env:
          WIZISHOP_USERNAME: ${{ secrets.WIZISHOP_USERNAME }}
          WIZISHOP_PASSWORD: ${{ secrets.WIZISHOP_PASSWORD }}
        run: uv run pytest

      - name: Minimize uv cache
        run: uv cache prune --ci
