name: CI

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run linter and type checker
        run: |
          uv run ruff format .
          uv run ruff check .
          uv run mypy .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        env:
          WIZISHOP_USERNAME: ${{ secrets.WIZISHOP_USERNAME }}
          WIZISHOP_PASSWORD: ${{ secrets.WIZISHOP_PASSWORD }}
        run: uv run pytest
