name: Release

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update pyproject.toml
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ github.ref_name }}\"/" pyproject.toml
          git add pyproject.toml
          git commit -m "Release version ${{ github.ref_name }}"
          git push
