name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update pyproject.toml
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ inputs.tag }}\"/" pyproject.toml

      - name: Release branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Release version ${{ inputs.tag }}"
          git checkout -b "release-${{ inputs.tag }}"
          git push origin "release-${{ inputs.tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update main
        run: |
          git checkout main
          git merge "release-${{ inputs.tag }}"
          git push origin main
          git push -d origin "release-${{ inputs.tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
