name: Release

on:
  release:
    types: [published]

permissions: write-all

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update pyproject.toml
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ github.ref_name }}\"/" pyproject.toml

      - name: Release branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Release version ${{ github.ref_name }}"
          git checkout -b "release-${{ github.ref_name }}"
          git push origin "release-${{ github.ref_name }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update main
        run: |
          git checkout main
          git merge "release-${{ github.ref_name }}"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
